project:
  type: website

website:
  title: "simmer"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Basics"
        contents:
          - href: one-die.qmd
            text: "1) rolling one die"
          - href: repeating.qmd
            text: "2) repeated actions"
          - href: two-dice.qmd
            text: "3) two dice"
      - section: "Advanced"
        contents:
          - href: loaded.qmd
            text: "Loaded dice"
          - href: coins.qmd
            text: "Coins"
          - href: examples.qmd
            text: "examples"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

