project:
  type: website
  resources:
    - "/art/"


website:
  title: "simmer"
  page-navigation: true

  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.html
        text: Introduction
      - section: "Basics"
        contents:
          - href: one-die.qmd
            text: "1) rolling one die"
          - href: repeating.qmd
            text: "2) repeated actions"
          - href: two-dice.qmd
            text: "3) two dice"
          - href: basics-commentary.qmd
            text: Commentary
      - text: "---"
      - section: "Not as basic"
        contents:
          - href: ten-dice.qmd
          - href: loaded.qmd
            text: "Loaded dice"
          - href: coins.qmd
            text: "Coins"
          - href: wait-time.qmd
          - href: n-dice.qmd
          - href: functions.qmd
          - href: commentary-redux.qmd
          - href: examples.qmd
            text: "examples"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

