```{=html}
    <script src="src/awash-functions.js"></script>
```

## Repeating many times

Let's change the program so that it repeats that process on its own, so that we don't have to press the button so many times.

Improve the example below.

-   Find a "repeat" block in one of the categories that will run those blocks 10 times.
-   Drag it into the workspace and make it enclose the blocks you want to repeat.
-   Run it and see what happens. (It's probably still not very evenly distributed.)
-   Change the number of repeats to a few hundred and run it again.
-   See if the graph shows that `item` has a more even distribution.

::: {column-page-right}
<script>
    const theURL = "https://codap.concord.org/releases/latest/static/dg/en/cert/index.html?di=https://codap.xyz/plugins/simmer/#shared=https%3A%2F%2Fcfm-shared.concord.org%2Fs94cqTewcfuowyxzxg0b%2Ffile.json";
    awash.liveDemoAt(theURL);
</script>
:::


The screen is getting crowded.
It's hard to work with the program, the graph, and the table at the same time. 

::: callout-tip
## pro tip: collapsing the code

In the `simmer` top bar you'll see a \[currently brown\] square showing four arrows pointing inward. Press it to collapse the program so you have more space for data analysis.

Then, when you want to program again, press the button to give yourself room to code.
:::


